### ISSUE TITLE
V0 Feature Completeness

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#297]
- [x] finish eth_secp256k1 integration 
- [ ] finish wiring mempool and associated view functions for json-rpc
- [x] ante handler and eth transaction simulation. 
- [x] verify QMS is working 
- [x] convert the 256 length queue to walking IAVL tree via historical que ry.
- [ ] verify MetaMask is Gucci.
- [ ] json rpc integration testing 
- [x] docs 
- [x] gas price oracle
- ...
- ...
