### ISSUE TITLE
epic(evm): ERC20 Middleware

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#31]
### Description: 
Create a middleware system to allow for ERC20 and ICS20 tokens to seemlessly interoperable.

**Functional Requirements**

* [ ] Token starts as ERC20 -> Handle escrowing and minting a native denominated balance.
* [ ] Token starts as ICS20 -> Handle deploy of a "BankModuleERC20".
* [ ] Handle precompile interop logic.

### Todos:
* [x] #35 
* [x] #36 
* [x] #12 
* [x] #33 
* [x] #32

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203747984824487/1203755067676663) by [Unito](https://www.unito.io)

**Comment by itsdevbear** [comment]
v0 complete
