### ISSUE TITLE
EPIC: Internal Monday Net

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#514]
Should be completed / merged prior to Monday. Let me know if any help is needed and I can jump in.

- [x] https://github.com/berachain/polaris/pull/492
- [ ] https://github.com/berachain/polaris/issues/493
- [ ] https://github.com/berachain/polaris/pull/476
- [ ] https://github.com/berachain/polaris/issues/495
- [ ] https://github.com/berachain/polaris/issues/494
- [x] https://github.com/berachain/polaris/pull/505
- [ ] https://github.com/berachain/polaris/pull/503
